# Generated by Django 2.1.3 on 2018-12-26 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('c_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('c_name', models.TextField(default='')),
                ('c_create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('c_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('c_create_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='c_create_user', to=settings.AUTH_USER_MODEL)),
                ('c_update_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='c_update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('p_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('p_name', models.TextField(default='')),
                ('p_sub_id', models.CharField(max_length=2)),
                ('p_create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('p_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Master.Classification')),
                ('p_create_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='p_create_user', to=settings.AUTH_USER_MODEL)),
                ('p_update_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='p_update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
