# Generated by Django 2.1.3 on 2019-02-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ammount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('credit', models.BooleanField(default=False)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.Purpose')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ammount', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
    ]
